version: "3"
services:
  react-app:
    # stdin_open: true
    # tty: true
    build:
      context: .
      dockerfile: Dockerfile.prod
      args: 
      - REACT_APP_NAME=MANH-prod
    ports:
      - "5000:80"
    volumes:
      - ./src:/app/src
    # env_file:
    #   - ./.env
